name: Create new release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name'
        required: true
      releaseNotes:
        description: 'Release notes'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    #  granting write permission to the contents of the repository
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # makes the entire history available (needed to obtain latest tag)

    - name: Tag commit
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git tag -a ${{ github.event.inputs.versionName }} -m "${{ github.event.inputs.releaseNotes }}"
        git push origin ${{ github.event.inputs.versionName }}
